server:
  port: 8765

spring:
  output:
    ansi:
      enabled: always
  redis:
    host: redis-gateway
    port: 6379
    password: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

jwt:
  secret: b84333cbb6e2c3885a7da2c87ce6a6ffc8f5993dca84b2f169dd990922922b25

