server:
  port: 8085
  forward-headers-strategy: framework

logging:
  level:
    org.springframework: info

spring:
  output:
    ansi:
      enabled: always
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200
      repositories:
        enabled: true
      security:
        username: elastic
        password: elastic
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.type.mapping]":
          event:com.example.event.TaskCreateEvent,
          event:com.example.event.ProjectCreateEvent,
          event:com.example.event.UserCreateEvent,
          event:com.example.event.TaskDeleteEvent,
          event:com.example.event.UserDeleteEvent,
          event:com.example.event.ProjectDeleteEvent
    topics:
      - createTask
      - createProject
      - createUser
      - deleteTask
      - deleteUser
      - deleteProject

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

jwt:
  secret: b84333cbb6e2c3885a7da2c87ce6a6ffc8f5993dca84b2f169dd990922922b25