server:
  port: 8088

spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          watch: true


#  http://localhost:8088/gateway-service/native [to check config server working correctly]